apiVersion: v1
kind: Service        # We're creating a Service
metadata:
  name: docker-implementation-service  # The name of the service
spec:
  selector:
    app: docker-implementation  # Must match the Deployment's label
  type: LoadBalancer             # Exposes the service outside the cluster
  ports:
    - protocol: TCP
      port: 80                   # External port (e.g. what the browser or curl hits)
      targetPort: 5000           # Internal app port (your container's Flask port)
